export const GET_COIN_DATA_REQUEST = "GET_COIN_DATA_REQUEST";
export const GET_COIN_DATA_SUCCESS = "GET_COIN_DATA_SUCCESS";
export const GET_COIN_DATA_FAIL = "GET_COIN_DATA_FAIL";

export const GET_COIN_HISTORY_REQUEST = "GET_COIN_HISTORY_REQUEST";
export const GET_COIN_HISTORY_SUCCESS = "GET_COIN_HISTORY_SUCCESS";
export const GET_COIN_HISTORY_FAIL = "GET_COIN_HISTORY_FAIL";

export const SET_INTERVAL_FORMAT = "SET_INTERVAL_FORMAT";
