export const ADD_COIN_TO_PORTFOLIO = "ADD_COIN_TO_PORTFOLIO";
export const REMOVE_COIN_FROM_PORTFOLIO = "REMOVE_COIN_FROM_PORTFOLIO";

export const SET_ACTIVE_COIN = "SET_ACTIVE_COIN";

export const UPDATE_COINS_DATA = "UPDATE_COINS_DATA";
export const UPDATE_PORTFOLIO = "UPDATE_PORTFOLIO";
