export const GET_ALL_CURRENCIES_REQUEST = "GET_ALL_CURRENCIES_REQUEST";
export const GET_ALL_CURRENCIES_SUCCESS = "GET_ALL_CURRENCIES_SUCCESS";
export const GET_ALL_CURRENCIES_FAIL = "GET_ALL_CURRENCIES_FAIL";

export const SET_POPULAR_CURRENCIES = "SET_POPULAR_CURRENCIES";
